import Head from "next/head";
import { getClient } from "../lib/sanity.server";
import groq from "groq";
import styled from 'styled-components'
import GridContainer from "../components/Grid/GridContainer";
import Search from "../components/Search/Search";

export async function getServerSideProps({ preview = false }) {
  const bookmark = await getClient(preview).fetch(groq`
    *[_type == 'bookmark']
  `);
  return {
    props: {
      bookmark,
    },
  };
}
const HomeContainer = styled.div`
  padding: 20px;
  margin: 20px;
`


const Home = ({bookmark}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <Search />
        <GridContainer bookmark={bookmark} />
      </HomeContainer>
    </>
  );
};



export default Home;
